#!/bin/sh
# The following lines instruct Slurm to allocate one GPU.
#SBATCH -p gpu
#SBATCH --gres=gpu:2
#SBATCH --mem=40gb
#SBATCH --time=60:00:00
#SBATCH -o f30k_ltd_%A_%a.out
#SBATCH --exclude=ilps-cn108
#SBATCH -c 18

# Set-up the environment.


conda activate image_caption_retrieval


# Start the experiment.
python /home/mbleeke1/image_caption_retrieval/feature_suppression/src/train.py --yaml_file /home/mbleeke1/image_caption_retrieval/feature_suppression/src/configs/f30k/f30k_ltd.yaml